all: test1 test2

test1: test1.cpp
	g++ -std=c++11 -O3 test1.cpp -L/opt/local/lib -lboost_timer-mt -lboost_system-mt -o test1

test2: test2.cpp
	g++ -std=c++11 -O3 test2.cpp -L/opt/local/lib -lboost_timer-mt -lboost_system-mt -o test2